### ISSUE TITLE
Update ansible role id to be correct

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/ansible-role-macfonts#2]
Official details (public domain) below:

````
Role: fubarhouse.macfonts
        description: Installs Apple Mac Applications using MAS-CLI
        active: True
        commit: b0311405b5324baca122e834b6c86ba9d08de90f
        commit_message: general cleanup
        commit_url: https://github.com/fubarhouse/ansible-role-macfonts/commit/b0311405b5324baca122e834b6c86ba9d08de90f
        company:
        created: 2016-11-28T09:50:49.163Z
        download_count: 2
        forks_count: 0
        github_branch:
        github_repo: ansible-role-macfonts
        github_user: fubarhouse
        id: 13836
        is_valid: True
        issue_tracker_url: http://example.com/issue/tracker
        license: MIT
        min_ansible_version: 2.1
        modified: 2016-11-28T11:28:51.529Z
        namespace: fubarhouse
        open_issues_count: 1
        path: ['/usr/local/etc/ansible/roles']
````
